import { defineConfig, type Plugin } from 'vite';
import react from '@vitejs/plugin-react';
import { promises as fs } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const rootDir = path.dirname(fileURLToPath(import.meta.url));

type TemplatesMap = {
  aliases: Record<string, string>;
  templates: Record<string, { body: string }>;
  list: string[];
};

function normalizeKey(value: string): string {
  return value
    .trim()
    .toLowerCase()
    .replace(/\.gitignore$/i, '')
    .replace(/[\s_.-]+/g, '')
    .replace(/[/]+/g, '');
}

// Serve /api/* requests from the generated templates-map.json during `vite dev`.
// This mirrors the static files generated by generate-templates.mjs but also
// supports multi-template concatenation (e.g. /api/Go,Node) which static files
// cannot handle.
function apiDevPlugin(): Plugin {
  let map: TemplatesMap | null = null;

  async function getMap(): Promise<TemplatesMap> {
    if (!map) {
      const raw = await fs.readFile(
        path.join(rootDir, 'public', 'data', 'templates-map.json'),
        'utf8',
      );
      map = JSON.parse(raw) as TemplatesMap;
    }

    return map;
  }

  return {
    name: 'api-dev',
    configureServer(server) {
      server.middlewares.use(async (req, res, next) => {
        const rawUrl = req.url ?? '';
        if (!rawUrl.startsWith('/api/')) {
          next();
          return;
        }

        const catchall = decodeURIComponent(rawUrl.slice('/api/'.length)).split('?')[0];

        res.setHeader('content-type', 'text/plain; charset=utf-8');
        res.setHeader('access-control-allow-origin', '*');
        res.setHeader('cache-control', 'no-store');

        try {
          const data = await getMap();

          if (!catchall) {
            res.writeHead(400);
            res.end('Usage: /api/list, /api/Node, /api/Go,Node\n');
            return;
          }

          if (catchall === 'list') {
            res.writeHead(200);
            res.end(`${data.list.join(',')}\n`);
            return;
          }

          const names = catchall.split(',').map((s) => s.trim()).filter(Boolean);
          const bodies: string[] = [];
          const missing: string[] = [];

          for (const name of names) {
            const canonical = data.templates[name]
              ? name
              : (data.aliases[normalizeKey(name)] ?? null);
            if (!canonical || !data.templates[canonical]) {
              missing.push(name);
            } else {
              bodies.push(data.templates[canonical].body);
            }
          }

          if (missing.length) {
            res.writeHead(404);
            res.end(`Unknown template(s): ${missing.join(', ')}\nSee /api/list for available names.\n`);
            return;
          }

          res.writeHead(200);
          res.end(`${bodies.join('\n\n').trim()}\n`);
        } catch {
          next();
        }
      });
    },
  };
}

export default defineConfig({
  base: './',
  plugins: [react(), apiDevPlugin()],
});